#!/usr/bin/env bash

#
# OS Specific Settings
#
case $(uname) in
  (Darwin)
  ;;
  (Linux)
    if [ -n $OCI_CONFIG_FILE ]; then is_oci_shell=true; fi
  ;;
  (SunOS)
  ;;
  (CYGWIN*)
  ;;
esac
# Bash on Windows
winchk=$(cat /proc/sys/kernel/osrelease)
if [[ $winchk == *"Microsoft"* ]]; then
  win=true;
  function _vpnfix(){ sed '1h;1d;$!H;$!d;G' /etc/resolv.conf > /tmp/resolv.temp;}
  alias vpnfix="_vpnfix && sudo mv /tmp/resolv.temp /etc/resolv.conf"
  alias cdc="cd /mnt/c"
fi

#
# Aliases
#
alias ll="ls -l"
alias la='ls -la'
alias q="exit"
alias cd.="cd .."
alias cd..="cd ../.."
alias cd...="cd ../../.."
alias dfg="df -BG"
alias psa=psadmin-plus

#
# Prompt
#
GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWDIRTYSTATE=true
source ~/.git-prompt.sh
source ~/.git-completion.sh
export PS1='\u@\[$(tput bold)\]\[$(tput setaf 2)\]\h\[$(tput sgr0)\]: \w$(__git_ps1 " [%s]") $ '

#
# Additional Tools
#
#export SQLPATH="$DOTFILES/sql/oracle" # SQL script path for sqlplus

#
# OCI
#
if [ $is_oci_shell ]; then
  source /etc/bashrc.cloudshell
  export TZ="/usr/share/zoneinfo/America/Chicago"
  #OCI_CLI_PROFILE
  export PS1='\[\033[90m\]┌[\[\033[37m\]\t\[\033[90m\]]-[\[\033[32m\]\u\[\033[90m\] at ☁️ ]-[\[\033[35m\]$OCI_CLI_PROFILE\[\033[90m\]]\n└[\[\033[34m\]\w\[\033[90m\]]\[\033[36m\]$(__git_ps1 " [%s]") \[\033[37m\]$ '
fi
