#!/usr/bin/env bash

#
# OS Specific Settings
#
case $(uname) in
  (Darwin)
  ;;
  (Linux)
    is_oci = true
  ;;
  (SunOS)
  ;;
  (CYGWIN*)
  ;;
esac
# Bash on Windows
winchk=$(cat /proc/sys/kernel/osrelease)
if [[ $winchk == *"Microsoft"* ]]; then
  win=true;
  function _vpnfix(){ sed '1h;1d;$!H;$!d;G' /etc/resolv.conf > /tmp/resolv.temp;}
  alias vpnfix="_vpnfix && sudo mv /tmp/resolv.temp /etc/resolv.conf"
  alias cdc="cd /mnt/c"
fi

#
# Aliases
#
alias ll="ls -l"
alias la='ls -la'
alias q="exit"
alias cd.="cd .."
alias cd..="cd ../.."
alias cd...="cd ../../.."
alias dfg="df -BG"
alias psa=psadmin-plus

#
# Prompt
#
# TODO - how can we have git hints in PS1 along with OCI?
if [ ! $is_oci ]; then
  source ~/.git-prompt.sh
  source ~/.git-completion.sh
  #GIT_PS1_SHOWCOLORHINTS=true
  GIT_PS1_SHOWDIRTYSTATE=true
  export PS1='\u@\[$(tput bold)\]\[$(tput setaf 2)\]\h\[$(tput sgr0)\]: \w$(__git_ps1 " [%s]") $ '
fi

#
# Additional Tools
#
#export SQLPATH="$DOTFILES/sql/oracle" # SQL script path for sqlplus

#
# OCI
#
if [ $is_oci ]; then
  source /etc/bashrc.cloudshell
fi
